# Generated by Django 2.1.9 on 2020-07-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesData',
            fields=[
                ('Cert_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Cert', models.FileField(upload_to='cert/')),
            ],
            options={
                'db_table': 'LecturesData',
            },
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('Course_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Trainer', models.CharField(max_length=100)),
                ('Course_Fee', models.CharField(max_length=50)),
                ('Course_Objective', models.CharField(max_length=1000)),
                ('Course_Eligibility', models.CharField(max_length=1000)),
                ('Course_Thumb', models.FileField(upload_to='coursethumb/')),
            ],
            options={
                'db_table': 'CourseData',
            },
        ),
        migrations.CreateModel(
            name='LecturesData',
            fields=[
                ('Lecture_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Course_ID', models.CharField(max_length=20)),
                ('Lecture_Name', models.CharField(max_length=100)),
                ('Lecture_Video', models.FileField(upload_to='courselectures/')),
            ],
            options={
                'db_table': 'LecturesData',
            },
        ),
        migrations.CreateModel(
            name='UserCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('Join_Date', models.CharField(default='08/07/2020', max_length=50)),
                ('User_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('User_FName', models.CharField(default='NA', max_length=50)),
                ('User_LName', models.CharField(default='NA', max_length=50)),
                ('User_Email', models.CharField(default='NA', max_length=70)),
                ('User_Phone', models.CharField(default='NA', max_length=15)),
                ('User_Password', models.CharField(default='NA', max_length=20)),
                ('Verify_Status', models.CharField(default='Unverified', max_length=12)),
                ('Status', models.CharField(default='Active', max_length=10)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
        migrations.CreateModel(
            name='UserLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('Course_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('Lecture_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('Lecture_Watched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('Review_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('User_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('User_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Course_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('Review', models.CharField(blank=True, max_length=5, null=True)),
                ('Feedback', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usercourses',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserData'),
        ),
    ]
