# Generated by Django 2.1.9 on 2020-06-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedata',
            old_name='Course_Contents',
            new_name='Course_Content',
        ),
    ]
