# Generated by Django 3.0.7 on 2020-06-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='27/06/2020', max_length=50),
        ),
    ]
