# Generated by Django 2.1.9 on 2020-07-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200708_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatesdata',
            old_name='Cert',
            new_name='Certificate',
        ),
        migrations.AlterModelTable(
            name='certificatesdata',
            table='CertificatesData',
        ),
    ]
