# Generated by Django 2.1.9 on 2020-07-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200708_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponData',
            fields=[
                ('Coupon_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Coupon_Name', models.CharField(max_length=200)),
                ('Coupon_Code', models.CharField(max_length=200)),
                ('Discount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='12/07/2020', max_length=50),
        ),
    ]
