# Generated by Django 2.1.9 on 2020-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200628_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturesData',
            fields=[
                ('Lecture_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Course_ID', models.CharField(max_length=20)),
                ('Lecture_Name', models.CharField(max_length=100)),
                ('Lecture_Video', models.FileField(upload_to='courselectures/')),
            ],
            options={
                'db_table': 'LecturesData',
            },
        ),
    ]
