# Generated by Django 2.1.9 on 2020-06-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200630_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='Course_Name',
        ),
    ]
