# Generated by Django 2.1.9 on 2020-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_usercourses_course_name'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='03/07/2020', max_length=50),
        ),
    ]
