# Generated by Django 2.1.9 on 2020-07-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200703_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('Course_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('Review', models.CharField(blank=True, max_length=5, null=True)),
                ('Feedback', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
