# Generated by Django 2.1.9 on 2020-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='User_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
