# Generated by Django 2.1.9 on 2020-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200705_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviews',
            name='id',
        ),
        migrations.AddField(
            model_name='userreviews',
            name='Review_ID',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Join_Date',
            field=models.CharField(default='06/07/2020', max_length=50),
        ),
    ]
