# Generated by Django 2.1.9 on 2020-07-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200706_1542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userreviews',
            table='UserReviews',
        ),
    ]
