# Generated by Django 2.1.9 on 2020-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200706_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreviews',
            name='Review_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='userreviews',
            table=None,
        ),
    ]
