# Generated by Django 2.1.9 on 2020-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_userreviews_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviews',
            name='id',
        ),
        migrations.AddField(
            model_name='userreviews',
            name='Review_ID',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
